2025-03-22 18:43:37,706 - ERROR - Signup failed: User already exists with this email
2025-03-22 18:43:37,706 - ERROR - Database error: 409: User already exists with this email
2025-03-22 18:43:37,707 - INFO - Database connection closed.
2025-03-22 18:45:32,397 - ERROR - Signup failed: User already exists with this email
2025-03-22 18:45:32,397 - ERROR - Database error: 409: User already exists with this email
2025-03-22 18:45:32,399 - INFO - Database connection closed.
2025-03-22 18:45:35,423 - ERROR - Signup failed: User already exists with this email
2025-03-22 18:45:35,423 - ERROR - Database error: 409: User already exists with this email
2025-03-22 18:45:35,426 - INFO - Database connection closed.
2025-03-22 18:46:37,455 - ERROR - Error occurred while verifying the password: argument 'hashed_password': 'str' object cannot be converted to 'PyBytes'
Traceback (most recent call last):
  File "/app/app/utils/hashing.py", line 27, in verify_password
    return bcrypt.checkpw(password.encode("utf-8"), hashed_password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'hashed_password': 'str' object cannot be converted to 'PyBytes'
2025-03-22 18:46:37,457 - CRITICAL - Unexpected error during login: Error occurred while verifying the password: argument 'hashed_password': 'str' object cannot be converted to 'PyBytes'
2025-03-22 18:46:37,458 - ERROR - Database error: 500: An unexpected error occurred: Error occurred while verifying the password: argument 'hashed_password': 'str' object cannot be converted to 'PyBytes'
2025-03-22 18:46:37,463 - INFO - Database connection closed.
2025-03-22 18:46:58,991 - ERROR - Error occurred while verifying the password: argument 'hashed_password': 'str' object cannot be converted to 'PyBytes'
Traceback (most recent call last):
  File "/app/app/utils/hashing.py", line 27, in verify_password
    return bcrypt.checkpw(password.encode("utf-8"), hashed_password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'hashed_password': 'str' object cannot be converted to 'PyBytes'
2025-03-22 18:46:58,993 - CRITICAL - Unexpected error during login: Error occurred while verifying the password: argument 'hashed_password': 'str' object cannot be converted to 'PyBytes'
2025-03-22 18:46:58,994 - ERROR - Database error: 500: An unexpected error occurred: Error occurred while verifying the password: argument 'hashed_password': 'str' object cannot be converted to 'PyBytes'
2025-03-22 18:46:58,996 - INFO - Database connection closed.
2025-03-22 18:48:31,191 - ERROR - Error occurred while verifying the password: argument 'hashed_password': 'str' object cannot be converted to 'PyBytes'
Traceback (most recent call last):
  File "/app/app/utils/hashing.py", line 27, in verify_password
    return bcrypt.checkpw(password.encode("utf-8"), hashed_password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'hashed_password': 'str' object cannot be converted to 'PyBytes'
2025-03-22 18:48:31,192 - CRITICAL - Unexpected error during login: Error occurred while verifying the password: argument 'hashed_password': 'str' object cannot be converted to 'PyBytes'
2025-03-22 18:48:31,193 - ERROR - Database error: 500: An unexpected error occurred: Error occurred while verifying the password: argument 'hashed_password': 'str' object cannot be converted to 'PyBytes'
2025-03-22 18:48:31,195 - INFO - Database connection closed.
2025-03-22 18:48:42,803 - ERROR - Signup failed: User already exists with this email
2025-03-22 18:48:42,803 - ERROR - Database error: 409: User already exists with this email
2025-03-22 18:48:42,805 - INFO - Database connection closed.
2025-03-22 18:49:03,364 - ERROR - Signup failed: User already exists with this email
2025-03-22 18:49:03,366 - ERROR - Database error: 409: User already exists with this email
2025-03-22 18:49:03,369 - INFO - Database connection closed.
2025-03-22 18:49:03,623 - ERROR - Signup failed: User already exists with this email
2025-03-22 18:49:03,624 - ERROR - Database error: 409: User already exists with this email
2025-03-22 18:49:03,627 - INFO - Database connection closed.
2025-03-22 18:49:03,707 - ERROR - Signup failed: User already exists with this email
2025-03-22 18:49:03,707 - ERROR - Database error: 409: User already exists with this email
2025-03-22 18:49:03,708 - INFO - Database connection closed.
2025-03-22 18:49:03,862 - ERROR - Signup failed: User already exists with this email
2025-03-22 18:49:03,862 - ERROR - Database error: 409: User already exists with this email
2025-03-22 18:49:03,864 - INFO - Database connection closed.
2025-03-22 18:49:04,024 - ERROR - Signup failed: User already exists with this email
2025-03-22 18:49:04,024 - ERROR - Database error: 409: User already exists with this email
2025-03-22 18:49:04,026 - INFO - Database connection closed.
2025-03-22 18:49:04,205 - ERROR - Signup failed: User already exists with this email
2025-03-22 18:49:04,205 - ERROR - Database error: 409: User already exists with this email
2025-03-22 18:49:04,207 - INFO - Database connection closed.
2025-03-22 18:51:55,001 - ERROR - Signup failed: {'message': 'User already exists with this username'}
2025-03-22 18:51:55,002 - ERROR - Database error: 409: {'message': 'User already exists with this username'}
2025-03-22 18:51:55,004 - INFO - Database connection closed.
